/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ["322_1"]: THREE.Mesh;
    ["322_2"]: THREE.Mesh;
  };
  materials: {
    ["Material #25"]: THREE.MeshStandardMaterial;
    ["Material #78"]: THREE.MeshStandardMaterial;
  };
};

export default function BioMechMutants(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    require("../assets/Model/Biomech_Mutant.glb")
  ) as GLTFResult;
  return (
    <group {...props} dispose={null} scale={3.2} position={[0, -2.8, 0]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["322_1"].geometry}
        material={materials["Material #25"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["322_2"].geometry}
        material={materials["Material #78"]}
      />
    </group>
  );
}

useGLTF.preload(require("../assets/Model/Biomech_Mutant.glb"));
